### PR TITLE
Updated based on UX feedbacks

### PR DESCRIPTION
**Pull request by ghost**
This checkin includes to the followings to make the horizon suse theme close to scc
1. Made the login icon and form side by side
2. Adjusted color  and border line of top navbar
3. Adjusted the navbar logo size and navbar width. 
4. Updated logo and logo-splash svg files
5. Adjusted breadcrumb background.
6. Adjusted sidebar height.

### CODE REVIEW

**Comment by rsalevsky** [comment]
@guglo Can you post a screenshot here? This usually speeds up the review.

**Comment by ghost** [comment]
@rsalevsky  the backend keystone I was tunneling to is down today. Once I find the working backend, I will capture the UI screenshots.

**Review by jeremy-moffitt — APPROVED** [review]
looks good to me, tested on http://suserock.us.to:28000  admin /  WR4Oulx00

**Comment by ghost** [comment]
horizon_login

horizon_dashboard

@rsalevsky  Please see the screenshots in case the horizon listed above is down.

**Review by rsalevsky — APPROVED** [review]

**Pull request merged**
